# Intro to Data Science with Pokemon 
***

### Arrays

In [1]:
food = ["Ham", "Cheese", "Bread", "Mayo", "Lettuce", "Tomato"]

In [3]:
print(food)

['Ham', 'Cheese', 'Bread', 'Mayo', 'Lettuce,Tomato']

In [4]:
print(food[2])

Bread

In [7]:
sliced_food_list = food[0:4]

In [6]:
print(sliced_food_list)

['Ham', 'Cheese', 'Bread']

### Import Libraries
***

In [8]:
import pandas as pd
import numpy as py
import seaborn as sb

In [9]:
print("PANDAS version" + pd.__version__)
print("numpy version" + py.__version__)
print("Seaborn version" + sb.__version__)

PANDAS version2.2.3
numpy version2.1.1
Seaborn version0.13.2

### Loading Data 
***

In [10]:
df = pd.read_csv('pokemon.csv')

### Displaying Full Data Frame 
***

In [11]:
#pd. set_option('display.max_rows', Name)

In [13]:
df.head(50)

,Per,Nat,Pokemon,HP,Atk,Def,SpA,SpD,Spe,Total,...,Catch,EXP,Evolve,Per.1,Nat.1,Joh,Hoe,Sin,Un,Pokemon.1
0,1.0,1.0,Bulbasaur,45,49,49,65,65,45,318,...,45,1059860,NaN,1.0,1.0,226.0,NaN,NaN,NaN,Bulbasaur
1,2.0,2.0,Ivysaur,60,62,63,80,80,60,405,...,45,1059860,Lv. 16,2.0,2.0,227.0,NaN,NaN,NaN,Ivysaur
2,3.0,3.0,Venusaur,80,82,83,100,100,80,525,...,45,1059860,Lv. 32,3.0,3.0,228.0,NaN,NaN,NaN,Venusaur
3,4.0,4.0,Charmander,39,52,43,60,50,65,309,...,45,1059860,NaN,4.0,4.0,229.0,NaN,NaN,NaN,Charmander
4,5.0,5.0,Charmeleon,58,64,58,80,65,80,405,...,45,1059860,Lv. 16,5.0,5.0,230.0,NaN,NaN,NaN,Charmeleon
5,6.0,6.0,Charizard,78,84,78,109,85,100,534,...,45,1059860,Lv. 36,6.0,6.0,231.0,NaN,NaN,NaN,Charizard
6,7.0,7.0,Squirtle,44,48,65,60,54,43,314,...,45,1059860,NaN,7.0,7.0,232.0,NaN,NaN,NaN,Squirtle
7,8.0,8.0,Wartortle,59,63,80,65,80,58,405,...,45,1059860,Lv. 16,8.0,8.0,233.0,NaN,NaN,NaN,Wartortle
8,9.0,9.0,Blastoise,79,83,100,85,105,78,530,...,45,1059860,Lv. 36,9.0,9.0,234.0,NaN,NaN,NaN,Blastoise
9,10.0,10.0,Caterpie,45,30,35,20,20,45,195,...,255,1000000,NaN,10.0,10.0,24.0,NaN,NaN,NaN,Caterpie
10,11.0,11.0,Metapod,50,20,55,25,25,30,205,...,120,1000000,Lv. 7,11.0,11.0,25.0,NaN,NaN,NaN,Metapod
11,12.0,12.0,Butterfree,60,45,50,80,80,70,385,...,45,1000000,Lv. 10,12.0,12.0,26.0,NaN,NaN,NaN,Butterfree
12,13.0,13.0,Weedle,40,35,30,20,20,50,195,...,255,1000000,NaN,13.0,13.0,27.0,NaN,NaN,NaN,Weedle
13,14.0,14.0,Kakuna,45,25,50,25,25,35,205,...,120,1000000,Lv. 7,14.0,14.0,28.0,NaN,NaN,NaN,Kakuna
14,15.0,15.0,Beedrill,65,80,40,40,80,75,380,...,45,1000000,Lv. 10,15.0,15.0,29.0,NaN,NaN,NaN,Beedrill
15,16.0,16.0,Pidgey,40,45,40,35,35,56,251,...,255,1059860,NaN,16.0,16.0,10.0,NaN,NaN,NaN,Pidgey
16,17.0,17.0,Pidgeotto,63,60,55,50,50,71,349,...,120,1059860,Lv. 18,17.0,17.0,11.0,NaN,NaN,NaN,Pidgeotto
17,18.0,18.0,Pidgeot,83,80,75,70,70,91,469,...,45,1059860,Lv. 36,18.0,18.0,12.0,NaN,NaN,NaN,Pidgeot
18,19.0,19.0,Rattata,30,56,35,25,35,72,253,...,255,1000000,NaN,19.0,19.0,17.0,NaN,NaN,NaN,Rattata
19,20.0,20.0,Raticate,55,81,60,50,70,97,413,...,127,1000000,Lv. 20,20.0,20.0,18.0,NaN,NaN,NaN,Raticate
20,21.0,21.0,Spearow,40,60,30,31,31,70,262,...,255,1000000,NaN,21.0,21.0,13.0,NaN,NaN,NaN,Spearow
21,22.0,22.0,Fearow,65,90,65,61,61,100,442,...,90,1000000,Lv. 20,22.0,22.0,14.0,NaN,NaN,NaN,Fearow
22,23.0,23.0,Ekans,30,60,44,40,54,55,283,...,255,1000000,NaN,23.0,23.0,50.0,NaN,NaN,NaN,Ekans
23,24.0,24.0,Arbok,60,85,69,65,79,80,438,...,90,1000000,Lv. 22,24.0,24.0,51.0,NaN,NaN,NaN,Arbok
24,26.0,25.0,Pikachu,35,55,30,50,40,90,300,...,190,1000000,Friendship,26.0,25.0,22.0,156.0,104.0,NaN,Pikachu
25,27.0,26.0,Raichu,60,90,55,90,80,100,475,...,75,1000000,Thunderstone,27.0,26.0,23.0,157.0,105.0,NaN,Raichu
26,28.0,27.0,Sandshrew,50,75,85,20,30,40,300,...,255,1000000,NaN,28.0,27.0,48.0,112.0,NaN,NaN,Sandshrew
27,29.0,28.0,Sandslash,75,100,110,45,55,65,450,...,90,1000000,Lv. 22,29.0,28.0,49.0,113.0,NaN,NaN,Sandslash
28,30.0,29.0,Nidoran ♀,55,47,52,40,40,41,275,...,235,1059860,NaN,30.0,29.0,95.0,NaN,NaN,NaN,Nidoran ♀
29,31.0,30.0,Nidorina,70,62,67,55,55,56,365,...,120,1059860,Lv. 16,31.0,30.0,96.0,NaN,NaN,NaN,Nidorina
30,32.0,31.0,Nidoqueen,90,82,87,75,85,76,495,...,45,1059860,Moon Stone,32.0,31.0,97.0,NaN,NaN,NaN,Nidoqueen
31,33.0,32.0,Nidoran ♂,46,57,40,40,40,50,273,...,235,1059860,NaN,33.0,32.0,98.0,NaN,NaN,NaN,Nidoran ♂
32,34.0,33.0,Nidorino,61,72,57,55,55,65,365,...,120,1059860,Lv. 16,34.0,33.0,99.0,NaN,NaN,NaN,Nidorino
33,35.0,34.0,Nidoking,81,92,77,85,75,85,495,...,45,1059860,Moon Stone,35.0,34.0,100.0,NaN,NaN,NaN,Nidoking
34,37.0,35.0,Clefairy,70,45,48,60,65,35,323,...,150,800000,Friendship,37.0,35.0,41.0,NaN,100.0,NaN,Clefairy
35,38.0,36.0,Clefable,95,70,73,85,90,60,473,...,25,800000,Moon Stone,38.0,36.0,42.0,NaN,101.0,NaN,Clefable
36,39.0,37.0,Vulpix,38,41,40,50,65,65,299,...,190,1000000,NaN,39.0,37.0,125.0,153.0,NaN,NaN,Vulpix
37,40.0,38.0,Ninetales,73,76,75,81,100,100,505,...,75,1000000,Fire Stone,40.0,38.0,126.0,154.0,NaN,NaN,Ninetales
38,42.0,39.0,Jigglypuff,115,45,20,45,25,20,270,...,170,800000,Friendship,42.0,39.0,44.0,138.0,NaN,NaN,Jigglypuff
39,43.0,40.0,Wigglytuff,140,70,45,75,50,45,425,...,50,800000,Moon Stone,43.0,40.0,45.0,139.0,NaN,NaN,Wigglytuff
40,44.0,41.0,Zubat,40,45,35,30,40,55,245,...,255,1000000,NaN,44.0,41.0,37.0,63.0,28.0,NaN,Zubat
41,45.0,42.0,Golbat,75,80,70,65,75,90,455,...,90,1000000,Lv. 22,45.0,42.0,38.0,64.0,29.0,NaN,Golbat
42,47.0,43.0,Oddish,45,50,55,75,65,30,320,...,255,1059860,NaN,47.0,43.0,83.0,88.0,NaN,NaN,Oddish
43,48.0,44.0,Gloom,60,65,70,85,75,40,395,...,120,1059860,Lv. 22,48.0,44.0,84.0,89.0,NaN,NaN,Gloom
44,49.0,45.0,Vileplume,75,80,85,100,90,50,480,...,45,1059860,Leaf Stone,49.0,45.0,85.0,90.0,NaN,NaN,Vileplume
45,51.0,46.0,Paras,35,70,55,45,55,25,285,...,190,1000000,NaN,51.0,46.0,70.0,NaN,NaN,NaN,Paras
46,52.0,47.0,Parasect,60,95,80,60,80,30,405,...,75,1000000,Lv. 24,52.0,47.0,71.0,NaN,NaN,NaN,Parasect
47,53.0,48.0,Venonat,60,55,50,40,55,45,305,...,190,1000000,NaN,53.0,48.0,108.0,NaN,NaN,NaN,Venonat
48,54.0,49.0,Venomoth,70,65,60,90,75,90,450,...,75,1000000,Lv. 31,54.0,49.0,109.0,NaN,NaN,NaN,Venomoth
49,55.0,50.0,Diglett,10,55,25,35,45,95,265,...,255,1000000,NaN,55.0,50.0,132.0,NaN,NaN,NaN,Diglett

### Accessing Columns 
***

In [14]:
df.Pokemon

0         Bulbasaur
1           Ivysaur
2          Venusaur
3        Charmander
4        Charmeleon
           ...
658          Kyurem
659          Keldeo
660    Meloetta (A)
661    Meloetta (P)
662        Genesect
Name: Pokemon, Length: 663, dtype: object

In [15]:
df.Pokemon[0]

'Bulbasaur'

In [16]:
df.Pokemon[0:3]

0    Bulbasaur
1      Ivysaur
2     Venusaur
Name: Pokemon, dtype: object

In [17]:
 pokemon_column[0]

NameError: name 'pokemon_column' is not defined